# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTZiD57u7higgumlz0btI1004t-p5q4Q
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from tensorflow.keras.models import load_model
import folium
from streamlit_folium import st_folium

# ─── CONFIG & SETUP ────────────────────────────────────────────────────────
st.set_page_config(page_title="Industrial Solar Rooftop Scout", layout="wide", page_icon="☀️")

# ค้นหาและโหลดโมเดล (ใช้ @st.cache_resource เพื่อให้โหลดแค่ครั้งแรกครั้งเดียว ไม่เปลืองแรม)
@st.cache_resource
def load_all_models():
    # เปลี่ยนเป็น path ไฟล์โมเดลของคุณ
    unet = load_model('u_net_model.h5', compile=False)
    gru = load_model('gru_model.h5', compile=False)
    with open('scaler.pkl', 'rb') as f:
        scaler = pickle.load(f)
    return unet, gru, scaler

try:
    unet_model, gru_model, scaler = load_all_models()
except Exception as e:
    st.error(f"❌ ไม่สามารถโหลดโมเดลได้ กรุณาตรวจสอบไฟล์ weights: {e}")

# ─── HELPER FUNCTIONS ──────────────────────────────────────────────────────
def get_satellite_image(lat, lng):
    """
    ฟังก์ชันดึงภาพดาวเทียมรอบพิกัดโรงงาน
    (ดึงจาก Google Static Maps API หรือ Earth Engine ตามที่ทำไว้ใน notebook)
    """
    # สมมุติตัวอย่างเป็น array เปล่าขนาดที่ U-Net ต้องการ (เช่น 256x256x3)
    # ในงานจริงต้องใช้โค้ดดึงภาพจากขั้นตอนที่ 2 ของไฟล์เดิมมาใส่ตรงนี้ครับ
    mock_img = np.zeros((256, 256, 3), dtype=np.uint8)
    return mock_img

def predict_roof_area(image, model):
    """
    ใช้ U-Net ทำ Segmentation หาพื้นที่หลังคา
    """
    # 1. Preprocess ภาพให้เข้ากับที่โมเดลต้องการ
    img_input = np.expand_dims(image / 255.0, axis=0) # Normalize และเพิ่ม Batch dimension
    # 2. Predict Mask
    mask = model.predict(img_input, verbose=0)[0]
    binary_mask = (mask > 0.5).astype(np.uint8)

    # 3. คำนวณพื้นที่ (ตร.ม.) ตามอัตราส่วนความละเอียดภาพ (Resolution) ของคุณ
    # สมมุติค่าตัวคูณพิกเซลละ 0.5 เมตร -> 1 พิกเซล = 0.25 ตร.ม.
    pixel_resolution = 0.25
    roof_pixels = np.sum(binary_mask)
    calculated_area = roof_pixels * pixel_resolution

    return binary_mask, calculated_area

def predict_solar_irradiance(gru_model, scaler):
    """
    ใช้ GRU พยากรณ์ค่ารังสีแสงอาทิตย์ล่วงหน้า
    """
    # ดึงข้อมูลรังสีฯ ย้อนหลังของพิกัดนั้น (X_va_dl ของคุณ)
    # ในที่นี้สมมุติข้อมูล Input ขนาด (1, timesteps, features)
    mock_input_scaled = np.random.rand(1, 12, 1) # สมมุติใช้ 12 เดือนย้อนหลัง

    # พยากรณ์
    pred_scaled = gru_model.predict(mock_input_scaled, verbose=0)

    # Inverse Transform กลับเป็นค่าจริง (รังสีแผ่พลังงาน)
    real_pred = scaler.inverse_transform(pred_scaled.reshape(-1, 1)).flatten()
    return real_pred

# ─── SIDEBAR & INPUTS ──────────────────────────────────────────────────────
st.sidebar.header("📍 ระบุข้อมูลโรงงาน")
lat_input = st.sidebar.number_input("Latitude", value=18.7883, format="%.6f")
lng_input = st.sidebar.number_input("Longitude", value=98.9853, format="%.6f")

analyze_btn = st.sidebar.button("🚀 เริ่มวิเคราะห์ระบบโซลาร์", type="primary")

# ─── MAIN DASHBOARD ────────────────────────────────────────────────────────
st.title("🛰️ Industrial Solar Rooftop Scout Dashboard")
st.write("ระบบ AI วิเคราะห์ศักยภาพและประเมินความคุ้มค่าการติดตั้งโซลาร์เซลล์สำหรับโรงงานอุตสาหกรรม")

if analyze_btn:
    with st.spinner("🔄 ระบบกำลังประมวลผลโมเดล AI..."):

        # 1. แสดงแผนที่พิกัดโรงงาน
        col1, col2 = st.columns([1, 1])
        with col1:
            st.subheader("🗺️ ที่ตั้งโรงงาน")
            m = folium.Map(location=[lat_input, lng_input], zoom_start=17)
            folium.Marker([lat_input, lng_input], popup="โรงงานที่เลือก").add_to(m)
            st_folium(m, width=500, height=300)

        # 2. ทำงานกับ U-Net (พื้นที่หลังคา)
        sat_img = get_satellite_image(lat_input, lng_input)
        roof_mask, roof_area = predict_roof_area(sat_img, unet_model)

        with col2:
            st.subheader("📐 ผลการวิเคราะห์พื้นที่หลังคา (U-Net)")
            st.metric(label="พื้นที่หลังคาที่ตรวจพบ", value=f"{roof_area:,.2f} ตร.ม.")

            # แสดงภาพ Mask ที่ U-Net ตัดได้
            fig, ax = plt.subplots(1, 2, figsize=(6, 3))
            ax[0].imshow(sat_img)
            ax[0].set_title("Original Image")
            ax[0].axis('off')
            ax[1].imshow(roof_mask.squeeze(), cmap='gray')
            ax[1].set_title("Predicted Roof Mask")
            ax[1].axis('off')
            st.pyplot(fig)

        st.markdown("---")

        # 3. 工作กับ GRU (พยากรณ์รังสีอาทิตย์และคำนวณกำลังผลิต)
        st.subheader("☀️ การพยากรณ์ค่ารังสีแสงอาทิตย์ล่วงหน้า (GRU)")

        forecast_values = predict_solar_irradiance(gru_model, scaler)

        # สร้าง DataFrame แสดงผลกราฟ
        months = [f"Month +{i+1}" for i in range(len(forecast_values))]
        df_forecast = pd.DataFrame({
            'Month': months,
            'Predicted Irradiance (kWh/m²/day)': forecast_values
        })

        col3, col4 = st.columns([2, 1])
        with col3:
            # พล็อตแนวโน้มรังสีแสงอาทิตย์
            st.line_chart(df_forecast.set_index('Month'))

        with col4:
            # คำนวณผลประโยชน์/ขนาดการติดตั้งเบื้องต้น (Financial & Technical ROI)
            st.markdown("### 📊 ประมาณการติดตั้งโซลาร์เซลล์")

            # สูตรคำนวณคร่าวๆ: พื้นที่หลังคา 10 ตร.ม. ติดตั้งได้ประมาณ 1 kWp
            potential_kwp = roof_area / 10.0
            avg_irradiance = np.mean(forecast_values)

            # พลังงานที่ผลิตได้ต่อปีโดยประมาณ = kWp * ค่ารังสีเฉลี่ย * PR(0.75) * 365 วัน
            annual_energy = potential_kwp * avg_irradiance * 0.75 * 365

            st.write(f"**ขนาดกำลังผลิตสูงสุดที่ติดตั้งได้:** {potential_kwp:,.2f} kWp")
            st.write(f"**ค่ารังสีแสงอาทิตย์เฉลี่ย:** {avg_irradiance:.2f} kWh/m²/day")
            st.write(f"**คาดการณ์พลังงานที่ผลิตได้:** {annual_energy:,.2f} kWh/ปี")

else:
    st.info("💡 กรุณาระบุพิกัด Latitude และ Longitude ที่เมนูด้านซ้าย แล้วกดปุ่ม 'เริ่มวิเคราะห์ระบบโซลาร์'")